config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "posts#index"

  resources :posts

  get 'post/reason', to: 'posts#reason', as: :reason
  get 'post/about_this', to: 'posts#about_this', as: :about_this

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

	validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

	def index
		@posts = Post.all
		@post = Post.new
	end

	def create 
		post_params = params[:post].permit(:body, :author)
		post = Post.new(post_params)
		if post.save
			flash[:notice] = "Thank you for sharing!"
			redirect_to root_path
		else
			redirect_to root_path

		end
	end 

	def reason
	end

	def about_this
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KindnessConfessions</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

		<nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
			<%= link_to root_path do %>
				<%= image_tag("KC_logo_edited.png", alt: "KindnessConfessions", width: 250, length: 250) %>
			<% end %>

			<ul class="navbar-nav ml-auto">
		    <li class="nav-item active">
		      <%= link_to "Why share?", reason_path, class: "nav-link" %>
		    </li>
		    <li class="nav-item">
		      <%= link_to "About this website", about_this_path, class: "nav-link" %>
		    </li>
		  </ul>
		</nav>
    
    <%= yield %>

    <br />
    <footer class="footer">
    	<div class="container-fluid">
    		<p>Kindness Confessions &copy; 2017</p>
    	</div>
    </footer>
  
  </body>
</html>

app/views/posts/about_this.html.erb
<a>This project is actually inspired by this trend that is most commonly seen in schools and institutions, such as SP confessions, TP confessions and so forth. I feel that people like to read people confessions on something, anonymously, on the web as it gives a space for them to reflect and write down their thoughts. 

And I was thinking, why does no one confess on something like an act of kindness?

Thus, I tried to do a mini project called the kindness confessions. </a>

app/views/posts/index.html.erb
<div class="container ">

	<div class="row justify-content-md-center">
		<div class="col-10">
			<%= form_for @post, url: posts_path, method: :post do |f| %>	

				<div class="question">
					<br />
					<p>Have you chance upon an act of kindness where you still remember it till today? </p>
					<p>Why not share it here!</p>
				</div>

				<div class="form-group">
					<%= f.text_area :body, 
							class: "form-control", 
							rows: "8", 
							placeholder: "e.g. Thank you yellow shirt guy who helped me return my wallet! " %>
				</div>

				<div>
					<%= f.label :From %>
					<button type="button" class="btn btn-secondary btn-sm" data-container="body" data-toggle="popover" data-placement="top" data-content="Your name will be saved as anonymous if no name is inputed.">
  					?
					</button>
					<%= f.text_field :author , placeholder: "Anonymous" %>
					<%= f.submit 'Submit'	%>
				</div>
					
			<% end %>
		</div>
	</div>

</div>

<br />

<div class="container">
	<div class="row justify-content-md-center">
		<div class="col-10">

		<% @posts.each do |post| %>
			<div class="card">
			  <div class="card-body">
					
					<%= post.id %>		
					<%= post.body %>
					<%= post.author %>

			  </div>
			</div>
			<br />
		<% end %>
		
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function () {
  	$('[data-toggle="popover"]').popover()
	})
</script>

app/views/posts/reason.html.erb
<a>Why share?

Why NOT! That's what I always say. 

When you share or write down an experience of an act of kindness, you show gratitude.

Gratitude is basically the quality of being thankful; readiness to show appreciation and to return kindness.

Psychologists Robert Emmons and Michael McCullough (2003) discovered people that wrote down experiences expressing gratitude ended up happier, much more optimistic about the future, and physically healthier—and they even exercised more.

Showing appreciation has been found in the study Emotion (2014)

References:
Emmons, R. A., & McCullough, M. E. (2003). Counting blessings versus burdens: An experimental investigation of gratitude and subjective well-being in daily life. Journal of Personality and Social Psychology, 84, 377–389. 
</a>